project:
    title: ""
    subtitle: ""
    overview: >
        
    features:
        - ""
        - ""
    tech:
        - "
    screenshots:
        - ""
    architecture: >
        
    challenges: >
        
    learned: >
        
    links:
        steam:
            name: ""
            link: ""